### PR TITLE
1.19.2 port

### PR DESCRIPTION
**Pull request by screret**
please merge to a new branch.
also, thanks for letting me do this!

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
Hello hello! we gave this one a test on our pack and thought you should know it doesn't like dedicated servers right now! 

I think you're accidentally accessing `net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler` in the modInitializer, which will work in singleplayer, but not on a dedi server. You probably just need to move something to the ClientModInitializer, but I haven't checked.

https://mclo.gs/AwZHAo3

**Comment by shdwchn10** [comment]
Hi! Thank you for your port! After latest server fix Im getting another error while trying to connect to server: `[19:04:04] [Netty Epoll Client IO #1/ERROR]: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '2' instead.`
image

<details> 
  <summary>full trace:</summary>
<pre><code>
[19:04:04] [Netty Epoll Client IO #1/ERROR]: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '2' instead.
[19:04:04] [Netty Epoll Client IO #1/ERROR]: Serializer: Error writing recipe to packet
java.lang.RuntimeException: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '2' instead.
	at net.minecraft.class_1856.handler$ecb000$ingredient-extension-api$ingredientextensionapi_fromNetwork(class_1856.java:3625) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8086(class_1856.java) ~[client-intermediary.jar:?]
	at io.github.tropheusj.serialization_hooks.ingredient.CombinedIngredient$Deserializer.fromNetwork(CombinedIngredient.java:109) ~[serialization_hooks-0.3.26-fc369d34b91c8f39.jar:?]
	at io.github.tropheusj.serialization_hooks.ingredient.IngredientDeserializer.tryDeserializeNetwork(IngredientDeserializer.java:97) ~[serialization_hooks-0.3.26-fc369d34b91c8f39.jar:?]
	at net.minecraft.class_1856.handler$glo000$serialization_hooks$fromNetwork(class_1856.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8086(class_1856.java) ~[client-intermediary.jar:?]
	at slimeknights.mantle.recipe.ingredient.SizedIngredient.read(SizedIngredient.java:164) ~[mantle-1.19.2-1.9.DEV.3ebf13eb-759cc61a6c550770.jar:?]
	at slimeknights.tconstruct.tools.recipe.ModifierRemovalRecipe$Serializer.fromNetworkSafe(ModifierRemovalRecipe.java:155) ~[Hephaestus-1.19.2-3.6.0+5.DEV.9a3efa283.jar:?]
	at slimeknights.tconstruct.tools.recipe.ModifierRemovalRecipe$Serializer.fromNetworkSafe(ModifierRemovalRecipe.java:137) ~[Hephaestus-1.19.2-3.6.0+5.DEV.9a3efa283.jar:?]
	at slimeknights.mantle.recipe.helper.LoggingRecipeSerializer.method_8122(LoggingRecipeSerializer.java:37) ~[mantle-1.19.2-1.9.DEV.3ebf13eb-759cc61a6c550770.jar:?]
	at net.minecraft.class_2788.method_17817(class_2788.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:171) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:184) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.<init>(class_2788.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:433) [client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:485) [client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) [client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[19:04:04] [Netty Epoll Client IO #1/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '2' instead.
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '2' instead.
	at net.minecraft.class_1856.handler$ecb000$ingredient-extension-api$ingredientextensionapi_fromNetwork(class_1856.java:3625) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8086(class_1856.java) ~[client-intermediary.jar:?]
	at io.github.tropheusj.serialization_hooks.ingredient.CombinedIngredient$Deserializer.fromNetwork(CombinedIngredient.java:109) ~[serialization_hooks-0.3.26-fc369d34b91c8f39.jar:?]
	at io.github.tropheusj.serialization_hooks.ingredient.IngredientDeserializer.tryDeserializeNetwork(IngredientDeserializer.java:97) ~[serialization_hooks-0.3.26-fc369d34b91c8f39.jar:?]
	at net.minecraft.class_1856.handler$glo000$serialization_hooks$fromNetwork(class_1856.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8086(class_1856.java) ~[client-intermediary.jar:?]
	at slimeknights.mantle.recipe.ingredient.SizedIngredient.read(SizedIngredient.java:164) ~[mantle-1.19.2-1.9.DEV.3ebf13eb-759cc61a6c550770.jar:?]
	at slimeknights.tconstruct.tools.recipe.ModifierRemovalRecipe$Serializer.fromNetworkSafe(ModifierRemovalRecipe.java:155) ~[Hephaestus-1.19.2-3.6.0+5.DEV.9a3efa283.jar:?]
	at slimeknights.tconstruct.tools.recipe.ModifierRemovalRecipe$Serializer.fromNetworkSafe(ModifierRemovalRecipe.java:137) ~[Hephaestus-1.19.2-3.6.0+5.DEV.9a3efa283.jar:?]
	at slimeknights.mantle.recipe.helper.LoggingRecipeSerializer.method_8122(LoggingRecipeSerializer.java:37) ~[mantle-1.19.2-1.9.DEV.3ebf13eb-759cc61a6c550770.jar:?]
	at net.minecraft.class_2788.method_17817(class_2788.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:171) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:184) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.<init>(class_2788.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:433) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:485) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:?]
	... 30 more
[19:04:04] [Netty Epoll Client IO #1/ERROR]: Twilight Forest: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '2' instead.
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Failed to deserialize ingredient! Expected a marker with value '601817315' or '-104387951'. Got '2' instead.
	at net.minecraft.class_1856.handler$ecb000$ingredient-extension-api$ingredientextensionapi_fromNetwork(class_1856.java:3625) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8086(class_1856.java) ~[client-intermediary.jar:?]
	at io.github.tropheusj.serialization_hooks.ingredient.CombinedIngredient$Deserializer.fromNetwork(CombinedIngredient.java:109) ~[serialization_hooks-0.3.26-fc369d34b91c8f39.jar:?]
	at io.github.tropheusj.serialization_hooks.ingredient.IngredientDeserializer.tryDeserializeNetwork(IngredientDeserializer.java:97) ~[serialization_hooks-0.3.26-fc369d34b91c8f39.jar:?]
	at net.minecraft.class_1856.handler$glo000$serialization_hooks$fromNetwork(class_1856.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8086(class_1856.java) ~[client-intermediary.jar:?]
	at slimeknights.mantle.recipe.ingredient.SizedIngredient.read(SizedIngredient.java:164) ~[mantle-1.19.2-1.9.DEV.3ebf13eb-759cc61a6c550770.jar:?]
	at slimeknights.tconstruct.tools.recipe.ModifierRemovalRecipe$Serializer.fromNetworkSafe(ModifierRemovalRecipe.java:155) ~[Hephaestus-1.19.2-3.6.0+5.DEV.9a3efa283.jar:?]
	at slimeknights.tconstruct.tools.recipe.ModifierRemovalRecipe$Serializer.fromNetworkSafe(ModifierRemovalRecipe.java:137) ~[Hephaestus-1.19.2-3.6.0+5.DEV.9a3efa283.jar:?]
	at slimeknights.mantle.recipe.helper.LoggingRecipeSerializer.method_8122(LoggingRecipeSerializer.java:37) ~[mantle-1.19.2-1.9.DEV.3ebf13eb-759cc61a6c550770.jar:?]
	at net.minecraft.class_2788.method_17817(class_2788.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:171) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:184) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.<init>(class_2788.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:433) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:485) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:?]
	... 30 more
[19:04:04] [Netty Epoll Client IO #1/INFO]: Disconnected from server, resetting proxy config values
</code></pre>
</details>

**Comment by ceidways** [comment]
Getting a different error when connecting to server
[30/05/2023 16:18:00 pm] Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:t
image

<details><summary>Log</summary>
<p>

```
[30/05/2023 17:00:41 pm] [Render thread/INFO] Connecting to 127.0.0.1, 25565
[30/05/2023 17:00:43 pm] [Netty Client IO #2/INFO] Connected to a modded server.
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[30/05/2023 17:00:46 pm] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[30/05/2023 17:00:46 pm] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[30/05/2023 17:00:46 pm] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[30/05/2023 17:00:46 pm] 	at java.base/java.lang.Thread.run(Thread.java:833)
[30/05/2023 17:00:46 pm] Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2960.<init>(class_2960.java:41)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2960.<init>(class_2960.java:46)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2540.method_10810(class_2540.java:634)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2788.method_17817(class_2788.java:40)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2540.method_34068(class_2540.java:171)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2540.method_34066(class_2540.java:184)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2788.<init>(class_2788.java:22)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:433)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2539.method_10783(class_2539.java:485)
[30/05/2023 17:00:46 pm] 	at net.minecraft.class_2543.decode(class_2543.java:32)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
[30/05/2023 17:00:46 pm] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
[30/05/2023 17:00:46 pm] 	... 36 more
[30/05/2023 17:00:46 pm] [Netty Client IO #2/ERROR] Exception occurred in netty pipeline
``` 

</p>
</details>

**Comment by Facni** [comment]
Is this closed? It would be really great to have a 1.19.2 port.

**Comment by Polarite** [comment]
main dev is working on 1.20 and the person opened this pr is busy with other projects as far as I know.

**Comment by cannon9009** [comment]
[crash-2023-06-22_06.23.35-client.txt](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/11832932/crash-2023-06-22_06.23.35-client.txt)
The 1.19.2 port has an incompatibility with some mods, but I can't tell what. All I know is it doesn't work with the modlist I have. The modlist is below:
[modlist.txt](https://github.com/Alpha-s-Stuff/TinkersConstruct/files/11832938/modlist.txt)

I know dev isn't working on this project right now but I thought I'd put this here just for when they come back to porting 1.19.2.

**Comment by AlphaMode** [comment]
Closing as this pr has gone stale

**Pull request closed without merging**
