### PR TITLE
Fixed wearing a brute/zombified piglin head causes the game to crash

### PR DESCRIPTION
**Pull request by K0LALA**
Fixed issue #137

### CODE REVIEW

**Comment by K0LALA** [comment]
Fixed issue #135

**Comment by ItsBrogan2k** [comment]
Hey @K0LALA, any chance I can get the fix for this in a .jar? :)

**Comment by K0LALA** [comment]
The author of the mod said he would take a look soon. I guess you just have to wait a little bit for a new version to come. Or you can clone the pull request and build it with Gradle.

**Comment by K0LALA** [comment]
Also made a pull request on Mantle port to fix issue #126 but since it is not on this repo I can't add to this PR

**Pull request merged**
