### PR TITLE
Inventory Tabs Compatibility

### LINKED ISSUE #6: [Compat] Inventory Tabs
### Minecraft Version

1.18.1

### Forge Version

Quilt 0.17.1-beta6 (lol)

### Mantle Version

N/A

### Tinkers' Construct Version

3.5.1.DEV.04887b6

### Problem description

When opening a UI such as the part builder or tinker's station, the cursor centers on the window. This is normal behvaviour for vanilla, but with [Inventory Tabs](https://modrinth.com/mod/inventory-tabs-updated) it becomes an inconvenience with seemingly an easy fix.

https://user-images.githubusercontent.com/55819817/180699729-f3a1a323-3994-4daa-94f5-2d61e0f14c19.mp4

)

### Suggested solution

Don't center the cursor, or, find out why the cursor is being centered in the first place (forcing itself to close and reopen the screen maybe?)

### Alternatives considered

Honestly if it's too hardbasket I just wouldn't do it.

### Additional context

_No response_

### Searched for existing enhancement?

Used the search bar

### PR DESCRIPTION
**Pull request by sleepingdragoninn**
Fixes #6 - Hides tinker's table tabs if inventory tabs is installed (by preventing them from being added in the first place)

image

Tabs aren't clickable in these screens right now, likely because the clickable area of the tables themselves needs to be shrunk (or something else) - I'll have to fix that up

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
Update on this one - I've done some more extensive testing and found that the clicking incompatibility is seemingly due to mantle's `MultiModuleScreen` messing around with `imagewidth`/`backgroundwidth`, which is being read by Inventory Tabs [here](https://github.com/Andrew6rant/InventoryTabs/blob/1.18.x/src/main/java/com/kqp/inventorytabs/tabs/TabManager.java#L103) and [here](https://github.com/Andrew6rant/InventoryTabs/blob/1.18.x/src/main/java/com/kqp/inventorytabs/tabs/render/TabRenderer.java#L190), and causing the valid tab region on the screen to be calculated incorrectly: see me clicking 'invisible' tabs here

https://user-images.githubusercontent.com/55819817/183025307-41c4561d-dfc0-47dd-803c-a77815a36440.mp4

I've confirmed that the tabs work nicely when using the Inventory Tabs keybind (tab)

Overall I'd still consider this better compat than base, and enough to potentially improve the rest on the other end 👍

**Comment by sleepingdragoninn** [comment]
Happy to merge in our opinionated opinion.

**Comment by AlphaMode** [comment]
I think there should be a config option to toggle between tinkers tab system and inventory tabs

**Comment by sleepingdragoninn** [comment]
Right yeah I could probably do that - problem is, the implementation on the
inventory tabs side actually has no way to be disabled (meaning there's
limitations either way)

For now we'll just set up a config option to not cut out tcon3's tabs if
disabled and see how that looks.

**Comment by sleepingdragoninn** [comment]
Added and defaulted to true.  As seen above I've documented the mantle ModularScreens issue on the InventoryTabs side. Happily default it to false before merging if need be but we still reckon this is the best option 👍 

Ah and we've kind of set the convention that compat config is only checked on initialize (because some compat options tend to only work on initialize) - If you'd prefer this one to check the config option during runtime, we can sort that out easily.

**Comment by Andrew6rant** [comment]
Alright, I think I may have found a way to more accurately provide the tab hitboxes. (the tab's tooltip hover hitbox is in the proper location, I just need to calculate the button using that system / the tab render system)

I have an idea for how I could provide configuration to which screens the tabs render on (using config values, `screenSupported()` and `tabOpenedRecently`), but I am not certain yet

**Comment by AlphaMode** [comment]
Is this ready to be merged?

**Comment by sleepingdragoninn** [comment]
Go ahead!

**Pull request merged**
